_wandb:
    value:
        cli_version: 0.26.0
        e:
            m91l9t41nw78a8c9n5rivmhqq8sukuln:
                codePath: SciML/træning.py
                codePathLocal: SciML/træning.py
                cpu_count: 32
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "76817485824"
                        used: "8539746304"
                email: andreasantoft244@gmail.com
                executable: /zhome/bf/5/186685/Andreas/Bachelorprojekt/.venv/bin/python
                git:
                    commit: 7d3e690d81f89e52745f294ee934aeeb3ff9819b
                    remote: git@github.com:bantoft/Bachelorprojekt.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-a1e81f9a-2fae-802e-705d-7df8c66d9e31
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-10aad3f8-838d-0d66-3be3-716c30101530
                host: n-62-12-19
                memory:
                    total: "810713284608"
                os: Linux-6.1.167-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /zhome/bf/5/186685/Andreas/Bachelorprojekt/SciML/træning.py
                python: CPython 3.12.13
                root: /zhome/bf/5/186685/Andreas/Bachelorprojekt
                startedAt: "2026-04-26T22:42:29.114496Z"
                writerId: m91l9t41nw78a8c9n5rivmhqq8sukuln
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 62
            "4": 3.12.13
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 4096
collocation_shape:
    value:
        num_t: 16
        num_x: 16
        num_z: 16
device:
    value: cuda
early_stopping_min_delta:
    value: 0.0001
early_stopping_patience:
    value: 10
epochs:
    value: 10
ic_shape:
    value:
        num_x: 32
        num_z: 64
incl_data:
    value: true
lr:
    value: 0.001
model_path:
    value: /zhome/bf/5/186685/Andreas/Bachelorprojekt/SciML/data/trained_pinn_2026-04-27_00-39-56.pt
standardized_fields:
    value:
        - lnn
        - lnpe
        - lnpi
        - phi
val_split:
    value: 0.1
w_bc:
    value: 1
w_data:
    value: 1
w_eq:
    value: 1
w_ic:
    value: 1
