_wandb:
    value:
        cli_version: 0.26.0
        e:
            pzsrxwjeqtdwr2ihw9j1igghy0jikdv5:
                codePath: SciML/træning.py
                codePathLocal: træning.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "959725387776"
                        used: "77337866240"
                email: andreasantoft244@gmail.com
                executable: /home/andreas_a/Desktop/Bachelorprojekt/.venv/bin/python3
                git:
                    commit: 6dc3dcd1338ad6ad191e78b52bcf8071171829e8
                    remote: https://github.com/bantoft/Bachelorprojekt.git
                gpu: NVIDIA GeForce RTX 5060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3840
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060
                      uuid: GPU-f6e53fd9-b99c-d3a1-443e-b8377a03a7a4
                host: somebody
                memory:
                    total: "16321654784"
                os: Linux-6.19.13-arch1-1-x86_64-with-glibc2.43
                program: /home/andreas_a/Desktop/Bachelorprojekt/SciML/træning.py
                python: CPython 3.12.13
                root: /home/andreas_a/Desktop/Bachelorprojekt/SciML
                startedAt: "2026-04-26T21:09:38.678070Z"
                writerId: pzsrxwjeqtdwr2ihw9j1igghy0jikdv5
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
                - 62
            "4": 3.12.13
            "5": 0.26.0
            "12": 0.26.0
            "13": linux-x86_64
batch_size:
    value: 2048
collocation_shape:
    value:
        num_t: 16
        num_x: 16
        num_z: 16
device:
    value: cuda
early_stopping_min_delta:
    value: 0.0001
early_stopping_patience:
    value: 10
epochs:
    value: 10
ic_shape:
    value:
        num_x: 32
        num_z: 64
incl_data:
    value: true
lr:
    value: 0.001
model_path:
    value: /home/andreas_a/Desktop/Bachelorprojekt/SciML/data/trained_pinn_2026-04-26_23-09-37.pt
standardized_fields:
    value:
        - lnn
        - lnpe
        - lnpi
        - phi
val_split:
    value: 0.1
w_bc:
    value: 1
w_data:
    value: 1
w_eq:
    value: 1
w_ic:
    value: 1
